### PR TITLE
Add missing enums

### PR DESCRIPTION
**Pull request by labishrestha2**
Added some missing enums that were causing unhandled exceptions as described in issue #81

### CODE REVIEW

**Comment by labishrestha2** [comment]
This PR is a proposed fix to Issue #81

**Comment by labishrestha2** [comment]
I went ahead and signed the CLA but it still shows up as unsigned. Please let me know if I need to do anything else. Thank you!

**Comment by bihanssen** [comment]
@labishrestha2 
the signing didn't go through due to your provided email address not matching a github account. See comment from CLA Assistant:

> [![CLA assistant check]
> **Labi Shrestha** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).
> You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/NordicSemiconductor/pc-ble-driver-py?pullRequest=80) it.

**Comment by labishrestha2** [comment]
Redoing to fix the CLA issue

**Pull request closed without merging**
