### PR TITLE
Add missing enums

### PR DESCRIPTION
**Pull request by labishrestha2**
Added some missing enums that were causing unhandled exceptions as described in issue #81

### CODE REVIEW

**Comment by bihanssen** [comment]
Thanks for the contribution.

**Comment by labishrestha2** [comment]
No Problem! :+1:

**Comment by labishrestha2** [comment]
Hi @bihanssen any ideas when the next version will be released? many thanks!

**Comment by bihanssen** [comment]
@labishrestha2 see previous [comment](https://github.com/NordicSemiconductor/pc-ble-driver-py/issues/68#issuecomment-461411019) regarding release. No new updates.

**Pull request merged**
