### PR TITLE
Revert "Duplicate vs discovered services when calling adapter.service_discovery()"

### PR DESCRIPTION
**Pull request by bihanssen**
Reverts NordicSemiconductor/pc-ble-driver-py#167
The change has been found to introduce regression failures in certain cases (NCP-3349)

### CODE REVIEW

**Comment by jupe** [comment]
This would be more than Wellcome reversion also for us. When merging please create quickly patch release.

**Comment by andrew-gillan** [comment]
Interesting. How does having duplicates in the database create issues? Is there a use case for needing these?

**Comment by jupe** [comment]
Haven't investigate any deeper under the hoods but something clearly breaks. Without this revert library raises following every time when trying activate DFU mode for a our DUT:
```
E pc_ble_driver_py.exceptions.NordicSemiException: CCCD not found
```
Note that in this case 16-bit customer part is 0x0000 which is also marked as `BLEUUID.Standard.unknown` and with #167 change it is ignored...

**Comment by jupe** [comment]
Any news ?

**Comment by bihanssen** [comment]
@jupe sorry about the delayed response. Would you be able to share some info about the issue you are experiencing. I'm not able to reproduce. You mention that the UUID is 0x0000 which is a bit special. Does the error happen when you attempt to enable notifications on that characteristic?

**Comment by ArtoTanskanen** [comment]
Hi! @bihanssen We have a custom service with short UUID=0x0000. Yes it is this enable_notification function which is failing since this service UUID 0x0000 is not found from: db_conns table, when calling: handle = self.db_conns[conn_handle].get_cccd_handle(uuid) at line 390 in ble_adapter.py.

**Comment by bihanssen** [comment]
@ArtoTanskanen, thanks for the info. I'll try again to reproduce.

**Review by kenr — APPROVED** [review]
Thanks!

**Comment by jupe** [comment]
@bihanssen did you able to reproduce this? Would like to understand if there is any side-effect with this revert. Anyway - thanks for taking this in. Could we get also release?

**Comment by bihanssen** [comment]
@jupe we chose to merge the reversion before having managed to do a reproduction as we are aiming for a release. Will potentially look more into this after the next release.

**Pull request merged**
