### PR TITLE
Feature/ble gatts char md fix

### PR DESCRIPTION
**Pull request by dangu**
This is a branch aiming to fix the issue discussed in this thread:
https://devzone.nordicsemi.com/f/nordic-q-a/70813/user-description-in-pc-ble-driver-py

The current status is that the user description can be written and the number of bytes are correct but the actual bytes are garbage.

### CODE REVIEW

**Comment by bihanssen** [comment]
@dangu this PR overlaps with #184, should 184 be closed?

**Comment by dangu** [comment]
@bihanssen I would like to keep them separated as #184 and #188 are handling different issues. #188 needs more work as the actual bytes written show up as garbage. Should I better rebase #188 to get rid of the overlapping commits?

**Comment by bihanssen** [comment]
@dangu ok no problem, let's keep them separate then.

**Review by kenr — APPROVED** [review]
Thanks!

**Pull request merged**
